#### Import numpy library

In [3]:
import numpy as np

#### Create an numpy array which holds scalar

In [6]:
s = np.array(5)

In [7]:
s.shape

()

In [8]:
x = s+3

In [9]:
x

8

#### Create a vector

In [10]:
v = np.array([3,5,6])

In [11]:
v.shape

(3,)

In [12]:
x = v[1]

In [13]:
x

5

#### Access items from second element onwards

In [14]:
x = v[1:]

In [15]:
x

array([5, 6])

#### Create a matrices 

In [18]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [19]:
m.shape

(3, 3)

In [21]:
print(m[0][0])

1


#### Create Tensors  3x3x2x1 tensor

In [26]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]], 
                [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [27]:
t.shape

(3, 3, 2, 1)

#### Changing Shapes

In [28]:
v = np.array([1,2,3,4])

In [29]:
v.shape

(4,)

In [30]:
v.reshape(1,4)

array([[1, 2, 3, 4]])

In [35]:
v.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [37]:
x = v[None, :]

In [38]:
x

array([[1, 2, 3, 4]])

In [39]:
x = v[:, None]

In [40]:
x

array([[1],
       [2],
       [3],
       [4]])

## Element wise matrices

In [44]:
values = [1,2,3,4,5]
x = np.array(values)
print(x)
print(x+5)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [45]:
x= np.multiply(values,5)

In [46]:
x

array([ 5, 10, 15, 20, 25])

In [51]:
x  = [1,2,3,4,5] * 5 # Looks wrong in material

In [52]:
x

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

## Matrix Multiplication

In [54]:
m = np.array([[1,2,3],[4,5,6]])

In [56]:
n = m* 0.25

In [57]:
m * n

array([[ 0.25,  1.  ,  2.25],
       [ 4.  ,  6.25,  9.  ]])

In [58]:
np.multiply(m ,n)

array([[ 0.25,  1.  ,  2.25],
       [ 4.  ,  6.25,  9.  ]])

In [61]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [63]:
np.dot(a,b)

array([[ 70,  80,  90],
       [158, 184, 210]])

In [64]:
np.matmul(a,b)

array([[ 70,  80,  90],
       [158, 184, 210]])

#### Though np.dot(a,b) and np.matmul(a,b) returns same values for two dimentional data, it differs for other data structures.So need to be careful while using these interchangebly. 